//
// Autogenerated by Thrift Compiler (0.9.2)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var thrift = require('../thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;

var Errors_ttypes = require('./Errors_types')
var Common_ttypes = require('./Common_types')
var Authentication_ttypes = require('./Authentication_types')
var Table_ttypes = require('./Table_types')


var ttypes = module.exports = {};
ttypes.ClientMetricType = {
  'Letency' : 1
};
ttypes.LatencyMetricType = {
  'ExecutionTime' : 1
};
ttypes.MetricKey = {
  'METER_METRIC_MIN' : 0,
  'READ_ALLOWED' : 1,
  'READ_THROTTLED' : 2,
  'WRITE_ALLOWED' : 3,
  'WRITE_THROTTLED' : 4,
  'ACTION_SUCCESS' : 5,
  'ACTION_CLIENT_ERROR' : 6,
  'ACTION_SYSTEM_ERROR' : 7,
  'METER_METRIC_MAX' : 49,
  'HISTOGRAM_METRIC_MIN' : 50,
  'CREATE_LATENCY' : 51,
  'DROP_LATENCY' : 52,
  'DESCRIBE_LATENCY' : 53,
  'ALTER_LATENCY' : 54,
  'ENABLE_LATENCY' : 55,
  'DISABLE_LATENCY' : 56,
  'METRICQUERY_LATENCY' : 57,
  'GET_LATENCY' : 58,
  'PUT_LATENCY' : 59,
  'INCREMENT_LATENCY' : 60,
  'DELETE_LATENCY' : 61,
  'SCAN_LATENCY' : 62,
  'BATCH_LATENCY' : 63,
  'HISTOGRAM_METRIC_MAX' : 100
};
ttypes.MetricType = {
  'COUNT' : 1,
  'M1_RATE' : 2,
  'M5_RATE' : 3,
  'M15_RATE' : 4,
  'MEAN' : 5,
  'STDDEV' : 6,
  'P50' : 7,
  'P75' : 8,
  'P95' : 9,
  'P98' : 10,
  'P99' : 11
};
ttypes.TimeSpanUnit = {
  'SECONDS' : 1,
  'MINUTES' : 2,
  'HOURS' : 3
};
AppInfo = module.exports.AppInfo = function(args) {
  this.appId = null;
  this.developerId = null;
  this.tableMappings = null;
  this.oauthAppMapping = null;
  this.appName = null;
  if (args) {
    if (args.appId !== undefined) {
      this.appId = args.appId;
    }
    if (args.developerId !== undefined) {
      this.developerId = args.developerId;
    }
    if (args.tableMappings !== undefined) {
      this.tableMappings = args.tableMappings;
    }
    if (args.oauthAppMapping !== undefined) {
      this.oauthAppMapping = args.oauthAppMapping;
    }
    if (args.appName !== undefined) {
      this.appName = args.appName;
    }
  }
};
AppInfo.prototype = {};
AppInfo.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.appId = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.developerId = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.MAP) {
        var _size0 = 0;
        var _rtmp34;
        this.tableMappings = {};
        var _ktype1 = 0;
        var _vtype2 = 0;
        _rtmp34 = input.readMapBegin();
        _ktype1 = _rtmp34.ktype;
        _vtype2 = _rtmp34.vtype;
        _size0 = _rtmp34.size;
        for (var _i5 = 0; _i5 < _size0; ++_i5)
        {
          var key6 = null;
          var val7 = null;
          key6 = input.readString();
          val7 = input.readString();
          this.tableMappings[key6] = val7;
        }
        input.readMapEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.MAP) {
        var _size8 = 0;
        var _rtmp312;
        this.oauthAppMapping = {};
        var _ktype9 = 0;
        var _vtype10 = 0;
        _rtmp312 = input.readMapBegin();
        _ktype9 = _rtmp312.ktype;
        _vtype10 = _rtmp312.vtype;
        _size8 = _rtmp312.size;
        for (var _i13 = 0; _i13 < _size8; ++_i13)
        {
          var key14 = null;
          var val15 = null;
          key14 = input.readString();
          val15 = input.readString();
          this.oauthAppMapping[key14] = val15;
        }
        input.readMapEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 5:
      if (ftype == Thrift.Type.STRING) {
        this.appName = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

AppInfo.prototype.write = function(output) {
  output.writeStructBegin('AppInfo');
  if (this.appId !== null && this.appId !== undefined) {
    output.writeFieldBegin('appId', Thrift.Type.STRING, 1);
    output.writeString(this.appId);
    output.writeFieldEnd();
  }
  if (this.developerId !== null && this.developerId !== undefined) {
    output.writeFieldBegin('developerId', Thrift.Type.STRING, 2);
    output.writeString(this.developerId);
    output.writeFieldEnd();
  }
  if (this.tableMappings !== null && this.tableMappings !== undefined) {
    output.writeFieldBegin('tableMappings', Thrift.Type.MAP, 3);
    output.writeMapBegin(Thrift.Type.STRING, Thrift.Type.STRING, Thrift.objectLength(this.tableMappings));
    for (var kiter16 in this.tableMappings)
    {
      if (this.tableMappings.hasOwnProperty(kiter16))
      {
        var viter17 = this.tableMappings[kiter16];
        output.writeString(kiter16);
        output.writeString(viter17);
      }
    }
    output.writeMapEnd();
    output.writeFieldEnd();
  }
  if (this.oauthAppMapping !== null && this.oauthAppMapping !== undefined) {
    output.writeFieldBegin('oauthAppMapping', Thrift.Type.MAP, 4);
    output.writeMapBegin(Thrift.Type.STRING, Thrift.Type.STRING, Thrift.objectLength(this.oauthAppMapping));
    for (var kiter18 in this.oauthAppMapping)
    {
      if (this.oauthAppMapping.hasOwnProperty(kiter18))
      {
        var viter19 = this.oauthAppMapping[kiter18];
        output.writeString(kiter18);
        output.writeString(viter19);
      }
    }
    output.writeMapEnd();
    output.writeFieldEnd();
  }
  if (this.appName !== null && this.appName !== undefined) {
    output.writeFieldBegin('appName', Thrift.Type.STRING, 5);
    output.writeString(this.appName);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

MetricData = module.exports.MetricData = function(args) {
  this.clientMetricType = null;
  this.metricName = null;
  this.value = null;
  this.timeStamp = null;
  if (args) {
    if (args.clientMetricType !== undefined) {
      this.clientMetricType = args.clientMetricType;
    }
    if (args.metricName !== undefined) {
      this.metricName = args.metricName;
    }
    if (args.value !== undefined) {
      this.value = args.value;
    }
    if (args.timeStamp !== undefined) {
      this.timeStamp = args.timeStamp;
    }
  }
};
MetricData.prototype = {};
MetricData.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.clientMetricType = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.metricName = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.I64) {
        this.value = input.readI64();
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.I64) {
        this.timeStamp = input.readI64();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

MetricData.prototype.write = function(output) {
  output.writeStructBegin('MetricData');
  if (this.clientMetricType !== null && this.clientMetricType !== undefined) {
    output.writeFieldBegin('clientMetricType', Thrift.Type.I32, 1);
    output.writeI32(this.clientMetricType);
    output.writeFieldEnd();
  }
  if (this.metricName !== null && this.metricName !== undefined) {
    output.writeFieldBegin('metricName', Thrift.Type.STRING, 2);
    output.writeString(this.metricName);
    output.writeFieldEnd();
  }
  if (this.value !== null && this.value !== undefined) {
    output.writeFieldBegin('value', Thrift.Type.I64, 3);
    output.writeI64(this.value);
    output.writeFieldEnd();
  }
  if (this.timeStamp !== null && this.timeStamp !== undefined) {
    output.writeFieldBegin('timeStamp', Thrift.Type.I64, 4);
    output.writeI64(this.timeStamp);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

ClientMetrics = module.exports.ClientMetrics = function(args) {
  this.metricDataList = null;
  if (args) {
    if (args.metricDataList !== undefined) {
      this.metricDataList = args.metricDataList;
    }
  }
};
ClientMetrics.prototype = {};
ClientMetrics.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.LIST) {
        var _size20 = 0;
        var _rtmp324;
        this.metricDataList = [];
        var _etype23 = 0;
        _rtmp324 = input.readListBegin();
        _etype23 = _rtmp324.etype;
        _size20 = _rtmp324.size;
        for (var _i25 = 0; _i25 < _size20; ++_i25)
        {
          var elem26 = null;
          elem26 = new ttypes.MetricData();
          elem26.read(input);
          this.metricDataList.push(elem26);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ClientMetrics.prototype.write = function(output) {
  output.writeStructBegin('ClientMetrics');
  if (this.metricDataList !== null && this.metricDataList !== undefined) {
    output.writeFieldBegin('metricDataList', Thrift.Type.LIST, 1);
    output.writeListBegin(Thrift.Type.STRUCT, this.metricDataList.length);
    for (var iter27 in this.metricDataList)
    {
      if (this.metricDataList.hasOwnProperty(iter27))
      {
        iter27 = this.metricDataList[iter27];
        iter27.write(output);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

MetricQueryRequest = module.exports.MetricQueryRequest = function(args) {
  this.tableName = null;
  this.startTime = null;
  this.stopTime = null;
  this.metricKey = null;
  this.metricType = null;
  this.downsampleInterval = null;
  this.downsampleTimeUnit = null;
  if (args) {
    if (args.tableName !== undefined) {
      this.tableName = args.tableName;
    }
    if (args.startTime !== undefined) {
      this.startTime = args.startTime;
    }
    if (args.stopTime !== undefined) {
      this.stopTime = args.stopTime;
    }
    if (args.metricKey !== undefined) {
      this.metricKey = args.metricKey;
    }
    if (args.metricType !== undefined) {
      this.metricType = args.metricType;
    }
    if (args.downsampleInterval !== undefined) {
      this.downsampleInterval = args.downsampleInterval;
    }
    if (args.downsampleTimeUnit !== undefined) {
      this.downsampleTimeUnit = args.downsampleTimeUnit;
    }
  }
};
MetricQueryRequest.prototype = {};
MetricQueryRequest.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.tableName = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.I64) {
        this.startTime = input.readI64();
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.I64) {
        this.stopTime = input.readI64();
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.I32) {
        this.metricKey = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 5:
      if (ftype == Thrift.Type.I32) {
        this.metricType = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 6:
      if (ftype == Thrift.Type.I32) {
        this.downsampleInterval = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 7:
      if (ftype == Thrift.Type.I32) {
        this.downsampleTimeUnit = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

MetricQueryRequest.prototype.write = function(output) {
  output.writeStructBegin('MetricQueryRequest');
  if (this.tableName !== null && this.tableName !== undefined) {
    output.writeFieldBegin('tableName', Thrift.Type.STRING, 1);
    output.writeString(this.tableName);
    output.writeFieldEnd();
  }
  if (this.startTime !== null && this.startTime !== undefined) {
    output.writeFieldBegin('startTime', Thrift.Type.I64, 2);
    output.writeI64(this.startTime);
    output.writeFieldEnd();
  }
  if (this.stopTime !== null && this.stopTime !== undefined) {
    output.writeFieldBegin('stopTime', Thrift.Type.I64, 3);
    output.writeI64(this.stopTime);
    output.writeFieldEnd();
  }
  if (this.metricKey !== null && this.metricKey !== undefined) {
    output.writeFieldBegin('metricKey', Thrift.Type.I32, 4);
    output.writeI32(this.metricKey);
    output.writeFieldEnd();
  }
  if (this.metricType !== null && this.metricType !== undefined) {
    output.writeFieldBegin('metricType', Thrift.Type.I32, 5);
    output.writeI32(this.metricType);
    output.writeFieldEnd();
  }
  if (this.downsampleInterval !== null && this.downsampleInterval !== undefined) {
    output.writeFieldBegin('downsampleInterval', Thrift.Type.I32, 6);
    output.writeI32(this.downsampleInterval);
    output.writeFieldEnd();
  }
  if (this.downsampleTimeUnit !== null && this.downsampleTimeUnit !== undefined) {
    output.writeFieldBegin('downsampleTimeUnit', Thrift.Type.I32, 7);
    output.writeI32(this.downsampleTimeUnit);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

TimeSeriesData = module.exports.TimeSeriesData = function(args) {
  this.tableName = null;
  this.metricKey = null;
  this.metricType = null;
  this.data = null;
  if (args) {
    if (args.tableName !== undefined) {
      this.tableName = args.tableName;
    }
    if (args.metricKey !== undefined) {
      this.metricKey = args.metricKey;
    }
    if (args.metricType !== undefined) {
      this.metricType = args.metricType;
    }
    if (args.data !== undefined) {
      this.data = args.data;
    }
  }
};
TimeSeriesData.prototype = {};
TimeSeriesData.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.tableName = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.I32) {
        this.metricKey = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.I32) {
        this.metricType = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.MAP) {
        var _size28 = 0;
        var _rtmp332;
        this.data = {};
        var _ktype29 = 0;
        var _vtype30 = 0;
        _rtmp332 = input.readMapBegin();
        _ktype29 = _rtmp332.ktype;
        _vtype30 = _rtmp332.vtype;
        _size28 = _rtmp332.size;
        for (var _i33 = 0; _i33 < _size28; ++_i33)
        {
          var key34 = null;
          var val35 = null;
          key34 = input.readI64();
          val35 = input.readDouble();
          this.data[key34] = val35;
        }
        input.readMapEnd();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

TimeSeriesData.prototype.write = function(output) {
  output.writeStructBegin('TimeSeriesData');
  if (this.tableName !== null && this.tableName !== undefined) {
    output.writeFieldBegin('tableName', Thrift.Type.STRING, 1);
    output.writeString(this.tableName);
    output.writeFieldEnd();
  }
  if (this.metricKey !== null && this.metricKey !== undefined) {
    output.writeFieldBegin('metricKey', Thrift.Type.I32, 2);
    output.writeI32(this.metricKey);
    output.writeFieldEnd();
  }
  if (this.metricType !== null && this.metricType !== undefined) {
    output.writeFieldBegin('metricType', Thrift.Type.I32, 3);
    output.writeI32(this.metricType);
    output.writeFieldEnd();
  }
  if (this.data !== null && this.data !== undefined) {
    output.writeFieldBegin('data', Thrift.Type.MAP, 4);
    output.writeMapBegin(Thrift.Type.I64, Thrift.Type.DOUBLE, Thrift.objectLength(this.data));
    for (var kiter36 in this.data)
    {
      if (this.data.hasOwnProperty(kiter36))
      {
        var viter37 = this.data[kiter36];
        output.writeI64(kiter36);
        output.writeDouble(viter37);
      }
    }
    output.writeMapEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

Snapshot = module.exports.Snapshot = function(args) {
  this.snapshotName = null;
  this.snapshotState = null;
  if (args) {
    if (args.snapshotName !== undefined) {
      this.snapshotName = args.snapshotName;
    }
    if (args.snapshotState !== undefined) {
      this.snapshotState = args.snapshotState;
    }
  }
};
Snapshot.prototype = {};
Snapshot.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.snapshotName = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.I32) {
        this.snapshotState = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Snapshot.prototype.write = function(output) {
  output.writeStructBegin('Snapshot');
  if (this.snapshotName !== null && this.snapshotName !== undefined) {
    output.writeFieldBegin('snapshotName', Thrift.Type.STRING, 1);
    output.writeString(this.snapshotName);
    output.writeFieldEnd();
  }
  if (this.snapshotState !== null && this.snapshotState !== undefined) {
    output.writeFieldBegin('snapshotState', Thrift.Type.I32, 2);
    output.writeI32(this.snapshotState);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

TableSnapshots = module.exports.TableSnapshots = function(args) {
  this.tableName = null;
  this.sysSnapshots = null;
  this.userSnapshots = null;
  if (args) {
    if (args.tableName !== undefined) {
      this.tableName = args.tableName;
    }
    if (args.sysSnapshots !== undefined) {
      this.sysSnapshots = args.sysSnapshots;
    }
    if (args.userSnapshots !== undefined) {
      this.userSnapshots = args.userSnapshots;
    }
  }
};
TableSnapshots.prototype = {};
TableSnapshots.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.tableName = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.LIST) {
        var _size38 = 0;
        var _rtmp342;
        this.sysSnapshots = [];
        var _etype41 = 0;
        _rtmp342 = input.readListBegin();
        _etype41 = _rtmp342.etype;
        _size38 = _rtmp342.size;
        for (var _i43 = 0; _i43 < _size38; ++_i43)
        {
          var elem44 = null;
          elem44 = new ttypes.Snapshot();
          elem44.read(input);
          this.sysSnapshots.push(elem44);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.LIST) {
        var _size45 = 0;
        var _rtmp349;
        this.userSnapshots = [];
        var _etype48 = 0;
        _rtmp349 = input.readListBegin();
        _etype48 = _rtmp349.etype;
        _size45 = _rtmp349.size;
        for (var _i50 = 0; _i50 < _size45; ++_i50)
        {
          var elem51 = null;
          elem51 = new ttypes.Snapshot();
          elem51.read(input);
          this.userSnapshots.push(elem51);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

TableSnapshots.prototype.write = function(output) {
  output.writeStructBegin('TableSnapshots');
  if (this.tableName !== null && this.tableName !== undefined) {
    output.writeFieldBegin('tableName', Thrift.Type.STRING, 1);
    output.writeString(this.tableName);
    output.writeFieldEnd();
  }
  if (this.sysSnapshots !== null && this.sysSnapshots !== undefined) {
    output.writeFieldBegin('sysSnapshots', Thrift.Type.LIST, 2);
    output.writeListBegin(Thrift.Type.STRUCT, this.sysSnapshots.length);
    for (var iter52 in this.sysSnapshots)
    {
      if (this.sysSnapshots.hasOwnProperty(iter52))
      {
        iter52 = this.sysSnapshots[iter52];
        iter52.write(output);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  if (this.userSnapshots !== null && this.userSnapshots !== undefined) {
    output.writeFieldBegin('userSnapshots', Thrift.Type.LIST, 3);
    output.writeListBegin(Thrift.Type.STRUCT, this.userSnapshots.length);
    for (var iter53 in this.userSnapshots)
    {
      if (this.userSnapshots.hasOwnProperty(iter53))
      {
        iter53 = this.userSnapshots[iter53];
        iter53.write(output);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

SnapshotTableView = module.exports.SnapshotTableView = function(args) {
  this.tableName = null;
  this.tableExist = null;
  this.deleteTime = null;
  if (args) {
    if (args.tableName !== undefined) {
      this.tableName = args.tableName;
    }
    if (args.tableExist !== undefined) {
      this.tableExist = args.tableExist;
    }
    if (args.deleteTime !== undefined) {
      this.deleteTime = args.deleteTime;
    }
  }
};
SnapshotTableView.prototype = {};
SnapshotTableView.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.tableName = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.BOOL) {
        this.tableExist = input.readBool();
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.I64) {
        this.deleteTime = input.readI64();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

SnapshotTableView.prototype.write = function(output) {
  output.writeStructBegin('SnapshotTableView');
  if (this.tableName !== null && this.tableName !== undefined) {
    output.writeFieldBegin('tableName', Thrift.Type.STRING, 1);
    output.writeString(this.tableName);
    output.writeFieldEnd();
  }
  if (this.tableExist !== null && this.tableExist !== undefined) {
    output.writeFieldBegin('tableExist', Thrift.Type.BOOL, 2);
    output.writeBool(this.tableExist);
    output.writeFieldEnd();
  }
  if (this.deleteTime !== null && this.deleteTime !== undefined) {
    output.writeFieldBegin('deleteTime', Thrift.Type.I64, 3);
    output.writeI64(this.deleteTime);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

QuotaInfo = module.exports.QuotaInfo = function(args) {
  this.accountId = null;
  this.tableNum = null;
  this.tableNumUsed = null;
  this.space = null;
  this.spaceUsed = null;
  this.readCapacity = null;
  this.readCapacityUsed = null;
  this.writeCapacity = null;
  this.writeCapacityUsed = null;
  if (args) {
    if (args.accountId !== undefined) {
      this.accountId = args.accountId;
    }
    if (args.tableNum !== undefined) {
      this.tableNum = args.tableNum;
    }
    if (args.tableNumUsed !== undefined) {
      this.tableNumUsed = args.tableNumUsed;
    }
    if (args.space !== undefined) {
      this.space = args.space;
    }
    if (args.spaceUsed !== undefined) {
      this.spaceUsed = args.spaceUsed;
    }
    if (args.readCapacity !== undefined) {
      this.readCapacity = args.readCapacity;
    }
    if (args.readCapacityUsed !== undefined) {
      this.readCapacityUsed = args.readCapacityUsed;
    }
    if (args.writeCapacity !== undefined) {
      this.writeCapacity = args.writeCapacity;
    }
    if (args.writeCapacityUsed !== undefined) {
      this.writeCapacityUsed = args.writeCapacityUsed;
    }
  }
};
QuotaInfo.prototype = {};
QuotaInfo.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.accountId = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.I32) {
        this.tableNum = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.I32) {
        this.tableNumUsed = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.I64) {
        this.space = input.readI64();
      } else {
        input.skip(ftype);
      }
      break;
      case 5:
      if (ftype == Thrift.Type.I64) {
        this.spaceUsed = input.readI64();
      } else {
        input.skip(ftype);
      }
      break;
      case 6:
      if (ftype == Thrift.Type.I64) {
        this.readCapacity = input.readI64();
      } else {
        input.skip(ftype);
      }
      break;
      case 7:
      if (ftype == Thrift.Type.I64) {
        this.readCapacityUsed = input.readI64();
      } else {
        input.skip(ftype);
      }
      break;
      case 8:
      if (ftype == Thrift.Type.I64) {
        this.writeCapacity = input.readI64();
      } else {
        input.skip(ftype);
      }
      break;
      case 9:
      if (ftype == Thrift.Type.I64) {
        this.writeCapacityUsed = input.readI64();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

QuotaInfo.prototype.write = function(output) {
  output.writeStructBegin('QuotaInfo');
  if (this.accountId !== null && this.accountId !== undefined) {
    output.writeFieldBegin('accountId', Thrift.Type.STRING, 1);
    output.writeString(this.accountId);
    output.writeFieldEnd();
  }
  if (this.tableNum !== null && this.tableNum !== undefined) {
    output.writeFieldBegin('tableNum', Thrift.Type.I32, 2);
    output.writeI32(this.tableNum);
    output.writeFieldEnd();
  }
  if (this.tableNumUsed !== null && this.tableNumUsed !== undefined) {
    output.writeFieldBegin('tableNumUsed', Thrift.Type.I32, 3);
    output.writeI32(this.tableNumUsed);
    output.writeFieldEnd();
  }
  if (this.space !== null && this.space !== undefined) {
    output.writeFieldBegin('space', Thrift.Type.I64, 4);
    output.writeI64(this.space);
    output.writeFieldEnd();
  }
  if (this.spaceUsed !== null && this.spaceUsed !== undefined) {
    output.writeFieldBegin('spaceUsed', Thrift.Type.I64, 5);
    output.writeI64(this.spaceUsed);
    output.writeFieldEnd();
  }
  if (this.readCapacity !== null && this.readCapacity !== undefined) {
    output.writeFieldBegin('readCapacity', Thrift.Type.I64, 6);
    output.writeI64(this.readCapacity);
    output.writeFieldEnd();
  }
  if (this.readCapacityUsed !== null && this.readCapacityUsed !== undefined) {
    output.writeFieldBegin('readCapacityUsed', Thrift.Type.I64, 7);
    output.writeI64(this.readCapacityUsed);
    output.writeFieldEnd();
  }
  if (this.writeCapacity !== null && this.writeCapacity !== undefined) {
    output.writeFieldBegin('writeCapacity', Thrift.Type.I64, 8);
    output.writeI64(this.writeCapacity);
    output.writeFieldEnd();
  }
  if (this.writeCapacityUsed !== null && this.writeCapacityUsed !== undefined) {
    output.writeFieldBegin('writeCapacityUsed', Thrift.Type.I64, 9);
    output.writeI64(this.writeCapacityUsed);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

