//
// Autogenerated by Thrift Compiler (0.9.2)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var thrift = require('../thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;

var Errors_ttypes = require('./Errors_types')


var ttypes = module.exports = {};
ttypes.ThriftProtocol = {
  'TCOMPACT' : 0,
  'TJSON' : 1,
  'TBINARY' : 2
};
Version = module.exports.Version = function(args) {
  this.major = 1;
  this.minor = 0;
  this.patch = '1da06945';
  this.comments = '';
  if (args) {
    if (args.major !== undefined) {
      this.major = args.major;
    }
    if (args.minor !== undefined) {
      this.minor = args.minor;
    }
    if (args.patch !== undefined) {
      this.patch = args.patch;
    }
    if (args.comments !== undefined) {
      this.comments = args.comments;
    }
  }
};
Version.prototype = {};
Version.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.major = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.I32) {
        this.minor = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.STRING) {
        this.patch = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.STRING) {
        this.comments = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Version.prototype.write = function(output) {
  output.writeStructBegin('Version');
  if (this.major !== null && this.major !== undefined) {
    output.writeFieldBegin('major', Thrift.Type.I32, 1);
    output.writeI32(this.major);
    output.writeFieldEnd();
  }
  if (this.minor !== null && this.minor !== undefined) {
    output.writeFieldBegin('minor', Thrift.Type.I32, 2);
    output.writeI32(this.minor);
    output.writeFieldEnd();
  }
  if (this.patch !== null && this.patch !== undefined) {
    output.writeFieldBegin('patch', Thrift.Type.STRING, 3);
    output.writeString(this.patch);
    output.writeFieldEnd();
  }
  if (this.comments !== null && this.comments !== undefined) {
    output.writeFieldBegin('comments', Thrift.Type.STRING, 4);
    output.writeString(this.comments);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

ttypes.DEFAULT_CLIENT_TIMEOUT = 10000;
ttypes.DEFAULT_MAX_CLIENT_TIMEOUT = 10000;
ttypes.DEFAULT_ADMIN_CLIENT_TIMEOUT = 30000;
ttypes.DEFAULT_CLIENT_CONN_TIMEOUT = 3000;
ttypes.API_ROOT_PATH = '/v1/api';
ttypes.AUTH_SERVICE_PATH = '/v1/api/auth';
ttypes.ADMIN_SERVICE_PATH = '/v1/api/admin';
ttypes.DEFAULT_THRIFT_HEADER = 'application/x-thrift';
ttypes.THRIFT_JSON_HEADER = 'application/x-thrift-json';
ttypes.THRIFT_COMPACT_HEADER = 'application/x-thrift-compact';
ttypes.THRIFT_BINARY_HEADER = 'application/x-thrift-binary';
ttypes.THRIFT_HEADER_MAP = {0 : 'application/x-thrift-compact',
1 : 'application/x-thrift-json',
2 : 'application/x-thrift-binary'
};
ttypes.HEADER_THRIFT_MAP = {'application/x-thrift-compact' : 0,
'application/x-thrift-json' : 1,
'application/x-thrift-binary' : 2,
'application/x-thrift' : 1
};
ttypes.HK_REQUEST_TIMEOUT = 'X-Xiaomi-Request-Timeout';
ttypes.HK_ERROR_CODE_HEADER = 'X-Xiaomi-Error-Code';
ttypes.MAX_CONTENT_SIZE = 524288;
