//
// Autogenerated by Thrift Compiler (0.9.2)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;

var Errors_ttypes = require('./Errors_types')
var Common_ttypes = require('./Common_types')


var BaseService = require('./BaseService')
var BaseServiceClient = BaseService.Client
var BaseServiceProcessor = BaseService.Processor
var ttypes = require('./Authentication_types');
//HELPER FUNCTIONS AND STRUCTURES

AuthService_createCredential_args = function(args) {
  this.xiaomiAppId = null;
  this.appUserAuthProvider = null;
  this.authToken = null;
  if (args) {
    if (args.xiaomiAppId !== undefined) {
      this.xiaomiAppId = args.xiaomiAppId;
    }
    if (args.appUserAuthProvider !== undefined) {
      this.appUserAuthProvider = args.appUserAuthProvider;
    }
    if (args.authToken !== undefined) {
      this.authToken = args.authToken;
    }
  }
};
AuthService_createCredential_args.prototype = {};
AuthService_createCredential_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.xiaomiAppId = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.I32) {
        this.appUserAuthProvider = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.STRING) {
        this.authToken = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

AuthService_createCredential_args.prototype.write = function(output) {
  output.writeStructBegin('AuthService_createCredential_args');
  if (this.xiaomiAppId !== null && this.xiaomiAppId !== undefined) {
    output.writeFieldBegin('xiaomiAppId', Thrift.Type.STRING, 1);
    output.writeString(this.xiaomiAppId);
    output.writeFieldEnd();
  }
  if (this.appUserAuthProvider !== null && this.appUserAuthProvider !== undefined) {
    output.writeFieldBegin('appUserAuthProvider', Thrift.Type.I32, 2);
    output.writeI32(this.appUserAuthProvider);
    output.writeFieldEnd();
  }
  if (this.authToken !== null && this.authToken !== undefined) {
    output.writeFieldBegin('authToken', Thrift.Type.STRING, 3);
    output.writeString(this.authToken);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

AuthService_createCredential_result = function(args) {
  this.success = null;
  this.se = null;
  if (args instanceof Errors_ttypes.ServiceException) {
    this.se = args;
    return;
  }
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
    if (args.se !== undefined) {
      this.se = args.se;
    }
  }
};
AuthService_createCredential_result.prototype = {};
AuthService_createCredential_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new ttypes.Credential();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.se = new Errors_ttypes.ServiceException();
        this.se.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

AuthService_createCredential_result.prototype.write = function(output) {
  output.writeStructBegin('AuthService_createCredential_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  if (this.se !== null && this.se !== undefined) {
    output.writeFieldBegin('se', Thrift.Type.STRUCT, 1);
    this.se.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

AuthServiceClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this._seqid = 0;
    this._reqs = {};
};
Thrift.inherits(AuthServiceClient, BaseServiceClient);
AuthServiceClient.prototype.seqid = function() { return this._seqid; }
AuthServiceClient.prototype.new_seqid = function() { return this._seqid += 1; }
AuthServiceClient.prototype.createCredential = function(xiaomiAppId, appUserAuthProvider, authToken, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_createCredential(xiaomiAppId, appUserAuthProvider, authToken);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_createCredential(xiaomiAppId, appUserAuthProvider, authToken);
  }
};

AuthServiceClient.prototype.send_createCredential = function(xiaomiAppId, appUserAuthProvider, authToken) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('createCredential', Thrift.MessageType.CALL, this.seqid());
  var args = new AuthService_createCredential_args();
  args.xiaomiAppId = xiaomiAppId;
  args.appUserAuthProvider = appUserAuthProvider;
  args.authToken = authToken;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

AuthServiceClient.prototype.recv_createCredential = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new AuthService_createCredential_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.se) {
    return callback(result.se);
  }
  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('createCredential failed: unknown result');
};
AuthServiceProcessor = exports.Processor = function(handler) {
  this._handler = handler
}
Thrift.inherits(AuthServiceProcessor, BaseServiceProcessor)
AuthServiceProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}

AuthServiceProcessor.prototype.process_createCredential = function(seqid, input, output) {
  var args = new AuthService_createCredential_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.createCredential.length === 3) {
    Q.fcall(this._handler.createCredential, args.xiaomiAppId, args.appUserAuthProvider, args.authToken)
      .then(function(result) {
        var result = new AuthService_createCredential_result({success: result});
        output.writeMessageBegin("createCredential", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new AuthService_createCredential_result(err);
        output.writeMessageBegin("createCredential", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.createCredential(args.xiaomiAppId, args.appUserAuthProvider, args.authToken,  function (err, result) {
      var result = new AuthService_createCredential_result((err != null ? err : {success: result}));
      output.writeMessageBegin("createCredential", Thrift.MessageType.REPLY, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

