//
// Autogenerated by Thrift Compiler (0.9.2)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


/**
 * SLFile格式存储类型
 */
declare enum SLFileType {
  'DATUM_MAP' = 1,
  'RC_BASIC' = 2,
}
  keyIdMap: { [k: number]: string; };

  constructor(args?: { keyIdMap?: { [k: number]: string; }; });
}
  keys: string[];
  types: { [k: string]: DataType; };

  constructor(args?: { keys?: string[]; types?: { [k: string]: DataType; }; });
}
  count: number;
  offset: number[];

  constructor(args?: { count?: number; offset?: number[]; });
}
  type: SLFileType;
  datumMapMeta: DatumMapMeta;
  rcBasicMeta: RCBasicMeta;

  constructor(args?: { type?: SLFileType; datumMapMeta?: DatumMapMeta; rcBasicMeta?: RCBasicMeta; });
}
  data: { [k: number]: Datum; };
  keyIdMap: { [k: number]: string; };

  constructor(args?: { data?: { [k: number]: Datum; }; keyIdMap?: { [k: number]: string; }; });
}
  values: Value[];

  constructor(args?: { values?: Value[]; });
}
  data: { [k: string]: Datum; };

  constructor(args?: { data?: { [k: string]: Datum; }; });
}
