//
// Autogenerated by Thrift Compiler (0.9.2)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var thrift = require('../thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;


var ttypes = module.exports = {};
ttypes.DEFAULT_CLIENT_SOCKET_TIMEOUT = 60000;
ttypes.DEFAULT_CLIENT_CONN_TIMEOUT = 30000;
ttypes.DEFAULT_SERVICE_ENDPOINT = 'http://awsbj0.emq.api.xiaomi.com';
ttypes.DEFAULT_SECURE_SERVICE_ENDPOINT = 'https://awsbj0.emq.api.xiaomi.com';
ttypes.QUEUE_SERVICE_PATH = '/v1/api/queue';
ttypes.MESSAGE_SERVICE_PATH = '/v1/api/message';
ttypes.STATISTICS_SERVICE_PATH = '/v1/api/statistics';
ttypes.XIAOMI_HEADER_PREFIX = 'x-xiaomi-';
ttypes.MI_DATE = 'x-xiaomi-date';
ttypes.GALAXY_ACCESS_KEY_ID = 'GalaxyAccessKeyId';
ttypes.SIGNATURE = 'Signature';
ttypes.AUTHORIZATION = 'authorization';
ttypes.CONTENT_MD5 = 'content-md5';
ttypes.CONTENT_TYPE = 'content-type';
ttypes.DATE = 'date';
ttypes.RANGE = 'range';
ttypes.USER_AGENT = 'user-agent';
ttypes.HOST = 'host';
ttypes.TIMESTAMP = 'x-xiaomi-timestamp';
ttypes.CONTENT_LENGTH = 'content-length';
