//
// Autogenerated by Thrift Compiler (0.9.2)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var thrift = require('../thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;


var ttypes = require('./Common_types');
//HELPER FUNCTIONS AND STRUCTURES

EMQBaseService_getServiceVersion_args = function(args) {
};
EMQBaseService_getServiceVersion_args.prototype = {};
EMQBaseService_getServiceVersion_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

EMQBaseService_getServiceVersion_args.prototype.write = function(output) {
  output.writeStructBegin('EMQBaseService_getServiceVersion_args');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

EMQBaseService_getServiceVersion_result = function(args) {
  this.success = null;
  this.e = null;
  if (args instanceof ttypes.GalaxyEmqServiceException) {
    this.e = args;
    return;
  }
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
    if (args.e !== undefined) {
      this.e = args.e;
    }
  }
};
EMQBaseService_getServiceVersion_result.prototype = {};
EMQBaseService_getServiceVersion_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new ttypes.Version();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.e = new ttypes.GalaxyEmqServiceException();
        this.e.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

EMQBaseService_getServiceVersion_result.prototype.write = function(output) {
  output.writeStructBegin('EMQBaseService_getServiceVersion_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  if (this.e !== null && this.e !== undefined) {
    output.writeFieldBegin('e', Thrift.Type.STRUCT, 1);
    this.e.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

EMQBaseService_validClientVersion_args = function(args) {
  this.clientVersion = null;
  if (args) {
    if (args.clientVersion !== undefined) {
      this.clientVersion = args.clientVersion;
    }
  }
};
EMQBaseService_validClientVersion_args.prototype = {};
EMQBaseService_validClientVersion_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.clientVersion = new ttypes.Version();
        this.clientVersion.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

EMQBaseService_validClientVersion_args.prototype.write = function(output) {
  output.writeStructBegin('EMQBaseService_validClientVersion_args');
  if (this.clientVersion !== null && this.clientVersion !== undefined) {
    output.writeFieldBegin('clientVersion', Thrift.Type.STRUCT, 1);
    this.clientVersion.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

EMQBaseService_validClientVersion_result = function(args) {
  this.e = null;
  if (args instanceof ttypes.GalaxyEmqServiceException) {
    this.e = args;
    return;
  }
  if (args) {
    if (args.e !== undefined) {
      this.e = args.e;
    }
  }
};
EMQBaseService_validClientVersion_result.prototype = {};
EMQBaseService_validClientVersion_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.e = new ttypes.GalaxyEmqServiceException();
        this.e.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

EMQBaseService_validClientVersion_result.prototype.write = function(output) {
  output.writeStructBegin('EMQBaseService_validClientVersion_result');
  if (this.e !== null && this.e !== undefined) {
    output.writeFieldBegin('e', Thrift.Type.STRUCT, 1);
    this.e.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

EMQBaseServiceClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this._seqid = 0;
    this._reqs = {};
};
EMQBaseServiceClient.prototype = {};
EMQBaseServiceClient.prototype.seqid = function() { return this._seqid; }
EMQBaseServiceClient.prototype.new_seqid = function() { return this._seqid += 1; }
EMQBaseServiceClient.prototype.getServiceVersion = function(callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_getServiceVersion();
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_getServiceVersion();
  }
};

EMQBaseServiceClient.prototype.send_getServiceVersion = function() {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('getServiceVersion', Thrift.MessageType.CALL, this.seqid());
  var args = new EMQBaseService_getServiceVersion_args();
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

EMQBaseServiceClient.prototype.recv_getServiceVersion = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new EMQBaseService_getServiceVersion_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.e) {
    return callback(result.e);
  }
  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('getServiceVersion failed: unknown result');
};
EMQBaseServiceClient.prototype.validClientVersion = function(clientVersion, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_validClientVersion(clientVersion);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_validClientVersion(clientVersion);
  }
};

EMQBaseServiceClient.prototype.send_validClientVersion = function(clientVersion) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('validClientVersion', Thrift.MessageType.CALL, this.seqid());
  var args = new EMQBaseService_validClientVersion_args();
  args.clientVersion = clientVersion;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

EMQBaseServiceClient.prototype.recv_validClientVersion = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new EMQBaseService_validClientVersion_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.e) {
    return callback(result.e);
  }
  callback(null)
};
EMQBaseServiceProcessor = exports.Processor = function(handler) {
  this._handler = handler
}
EMQBaseServiceProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}

EMQBaseServiceProcessor.prototype.process_getServiceVersion = function(seqid, input, output) {
  var args = new EMQBaseService_getServiceVersion_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.getServiceVersion.length === 0) {
    Q.fcall(this._handler.getServiceVersion)
      .then(function(result) {
        var result = new EMQBaseService_getServiceVersion_result({success: result});
        output.writeMessageBegin("getServiceVersion", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new EMQBaseService_getServiceVersion_result(err);
        output.writeMessageBegin("getServiceVersion", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.getServiceVersion( function (err, result) {
      var result = new EMQBaseService_getServiceVersion_result((err != null ? err : {success: result}));
      output.writeMessageBegin("getServiceVersion", Thrift.MessageType.REPLY, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

EMQBaseServiceProcessor.prototype.process_validClientVersion = function(seqid, input, output) {
  var args = new EMQBaseService_validClientVersion_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.validClientVersion.length === 1) {
    Q.fcall(this._handler.validClientVersion, args.clientVersion)
      .then(function(result) {
        var result = new EMQBaseService_validClientVersion_result({success: result});
        output.writeMessageBegin("validClientVersion", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new EMQBaseService_validClientVersion_result(err);
        output.writeMessageBegin("validClientVersion", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.validClientVersion(args.clientVersion,  function (err, result) {
      var result = new EMQBaseService_validClientVersion_result((err != null ? err : {success: result}));
      output.writeMessageBegin("validClientVersion", Thrift.MessageType.REPLY, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

